<?php

/*

type: layout

name: Feature 43

position: 43

categories: Features

*/

?>

<?php
if (!$classes['padding_top']) {
    $classes['padding_top'] = 'mw-p-t-80';
}
if (!$classes['padding_bottom']) {
    $classes['padding_bottom'] = '';
}

$layout_classes = ' ' . $classes['padding_top'] . ' ' . $classes['padding_bottom'] . ' ';
?>

<section class="section section-md py-5 <?php print $layout_classes; ?> edit safe-mode nodrop" field="layout-feature-skin-43-<?php print $params['id'] ?>" rel="module">
    <div class="container">
        <div class="timeline mw-timeline cloneable">
            <div class="mw-timeline-item">
                <i class="fa fa-skyatlas" style="font-size: 40px;"></i>
                <h5 class="my-3">Create a Wallet</h5>
                <p>Contact us and describe your problem We are ready to help</p>
            </div>

            <div class="mw-timeline-item cloneable">
                <i class="mw-micon-Data-Download" style="font-size: 40px;"></i>
                <h5 class="my-3">Save Your Seed Phrase</h5>
                <p>A seed phrase is a series of words generated by your cryptocurrency wallet that give you access to the crypto associated with that wallet.</p>
            </div>

            <div class="mw-timeline-item cloneable">
                <i class="fa fa-connectdevelop" style="font-size: 40px;"></i>
                <h5 class="my-3">Connect Your Wallet</h5>
                <p>Hundreds of dApp's use Wallet Connect to connect with wallets. Give users the choice to use your dApp with their favorite wallet on any device.</p>
            </div>

            <div class="mw-timeline-item cloneable">
                <i class="fa fa-btc" style="font-size: 40px;"></i>
                <h5 class="my-3">Buy Crypto</h5>
                <p>The most popular venues to buy bitcoins are cryptocurrency exchanges, brokerages (crypto and mainstream), and payment services like Paypal.</p>
            </div>
        </div>
    </div>
</section>
